services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: LetMeIn
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  be:
    build: ./be
    container_name: signup-be
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/appdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: LetMeIn
      SPRING_UPLOADS: /storage
      SPRING_PROFILES_ACTIVE: "docker"
      JWT_SECRET: "changeitchangeitchangeitchangeitchangeitchangeit"
      JWT_VALID_MINUTES: "180"
      INIT_EMAIL: fake@fake.com
      INIT_NAME: admin
      INIT_PASSWORD: changeit
      INIT_ENABLED: false
      ALLOWED_ORIGINS: http://localhost:81
      MAIL_HOST: host
      MAIL_PORT: 1
      MAIL_ADDR: mailhere
      MAIL_PASSWD: passwdhere
      MAIL_SOURCE_ADDR: sourcehere
      WEB_ORIGIN: example.com
    volumes:
      - ./uploads:/storage
  fe:
    build: ./fe
    container_name: signup-fe
    ports:
      - "81:80"
    depends_on:
      - be

volumes:
  pgdata: {}
