services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: plsdonthackme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: sign-up-be:latest
    ports:
      - "8080:8080"
    volumes:
      - ./uploads/sign-videos:/uploads/sign-videos

    environment:
      - SPRING_APPLICATION_JSON={"storage":{"location":"/uploads/sign-videos"}}

volumes:
  pgdata: {}